# -*- coding: utf-8 -*-
"""lab3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14iQZuGf4nkK-wDdtf4x_Vr-vTXuanmrP
"""

#1 номер
a=input()
if int(a)==1:
  print('январь')
elif int(a)==2:
  print('февраль')
elif int(a)==3:
  print('март')
elif int(a)==4:
  print('апрель')
elif int(a)==5:
  print('май')
elif int(a)==6:
  print('июнь')
elif int(a)==7:
  print('июль')
elif int(a)==8:
  print('август')
elif int(a)==9:
  print('сентябрь')
elif int(a)==10:
  print('октябрь')
elif int(a)==11:
  print('ноябрь')
elif int(a)==12:
  print('декабрь')

#2 number
a=input()
if int(a)%2==0:
  print('четное',a)
else:
  print('нечетное',a)

#3 number
a=input()
if int(a)>40:
  print('stonks')
else:
  print('not stonks')

#4 number
def is_year_leap(year):
  if year%4==0 :
    return True
  else:
    return False
a=int(input("введите год:"))
is_year_leap(a)

#5 number
cnt=set()
def is_prime(n):
  for x in range(1,int(n**0.5)+1):
    if n%x==0:
      cnt.add(n)
      cnt.add(x)
  if len(cnt)>2:
    return False
  else:
    return True
a=int(input())
is_prime(a)

#6 number
a=int(input("rrr:"))
b=int(input('ppp:'))
c=0
if a/b==3.6 or (((-138/2)**1.3)<=b<=((-69/(28)**5.1)*4)):
  c=a
  a=b
  b=c
else:
  print("")
print(a)
print(b)

#7 number
chet=0
otric=0
promejutok=0
unikalinue=set()
for x in range(5):
  a=int(input("Введи число:"))
  if a%2==0:
    chet+=1
  if a<0:
    otric+=1
  if a>=-256 and a<=1024:
    promejutok+=1
    unikalinue.add(a)
if len(unikalinue)<5:
  print("не все числа уникальные")
else:
  print("все числа уникальные")
print("четных:",chet,"отрицательных:",otric,"входящих в промежуток:",promejutok)